## mysql镜像版本
## ref: https://hub.docker.com/r/library/mysql/tags/
##
mysqlImage: mysql:5.7.13
# xtraBackupImage: gcr.io/google-samples/xtrabackup:1.0（需翻墙）
xtraBackupImage: anjia0532/google-samples.xtrabackup:1.0

service:
  ## 声明服务类型
  ## 参考: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services---service-types
  # type: ClusterIP
  type: NodePort
  port: 3306

mysqlha:
  replicaCount: 3

  ## MySQLroot用户密码
  ##
  # mysqlRootPassword: ## 默认: 随机十个字符串

  ## MySQL主从复制用户名和密码
  ##
  mysqlReplicationUser: repl
  # mysqlReplicationPassword:

  ## 创建一个普通用户
  ##
  # mysqlUser:
  # mysqlPassword: ## 默认:随机十个字符串


  ## 是否允许匿名访问
  ##
  # mysqlAllowEmptyPassword: true

  ## 创建一个数据库，并在启动时授予用户所有权限，如果有需要
  # mysqlDatabase:

## 使用持久卷来持久化
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  ## 如果定义了存储类名称
  ## 如果设置为"-"或者""将禁用动态配置
  ## 如果未定义或者设置为空将使用默认配置(gp2 on AWS, azure-disk on
  ## Azure, standard on GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessModes:
  - ReadWriteOnce
  size: 10Gi
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
