name: kibana
version: 0.8.0
appVersion: 6.3.1
description: Kibana is an open source data visualization plugin for Elasticsearch
keywords:
- 日志组件
maintainers:
- name: compleatang
  email: casey@monax.io
sources:
- https://github.com/elastic/kibana
engine: gotpl
home: https://www.elastic.co/products/kibana
